Don't abort on error. Handle bz2 and tbz, tbz optionally including *.gz files.

diff --git a/bin/missing-approve b/bin/missing-approve
--- a/bin/missing-approve
+++ b/bin/missing-approve
@@ -28,7 +28,9 @@ STATUS=$DIR/status
 POLICY=$(basename $(readlink $POLICYDB/current))
 CODE=$POLICYDB/$POLICY/code
 
-error () { echo "Error: $1"; exit 1; }
+exit_code=0;
+
+error () { echo "Error: $1" >&2; exit_code=1; }
 missing () { echo $1; }
 
 cd $CODE || error 
@@ -60,11 +62,18 @@ for device in * ; do
     lcode=$POLICYDB/$last/code/$device
     
     if [ -f $lcode ] ; then 
-	diff -I 'Generated by' -q $lcode $CODE/$device > /dev/null
+	cat $lcode
+    elif [ -f $lcode.bz2 ] ; then
+ 	bzcat $lcode.bz2 
     elif [ -f $lcode.gz ] ; then
-	zcat $lcode.gz | diff -I 'Generated by' -q - $CODE/$device > /dev/null
+ 	zcat $lcode.gz 
+    elif [ -f $POLICYDB/$last.tbz ] ; then
+	tar -O -xjf $POLICYDB/$last.tbz *$last/code/$device* 
     else
 	error "Missing $lcode"
-    fi || 
-    missing $device
+	continue
+    fi | diff -I 'Generated by' -q - $CODE/$device > /dev/null ||
+    missing $device; 
 done
+
+exit $exit_code
